package pe.com.tienda.vista;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.Dimension;
import java.sql.Date;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import pe.com.tienda.bean.Articulo;
import pe.com.tienda.bean.Cliente;
import pe.com.tienda.bean.Empleado;
import pe.com.tienda.dao.ArticuloDAO;
import pe.com.tienda.dao.ClienteDAO;
import pe.com.tienda.dao.EmpleadoDAO;
import pe.com.tienda.dao.PedidoDAO;

/**
 *
 * @author Sistema
 */
public class JFrameTarea extends javax.swing.JFrame {

    private static ArrayList<Articulo> list_articles = new ArrayList<>();
    private static Articulo article_selected;
    private static ArrayList<Integer> idlist_workers = new ArrayList<>();
    private static int index = 0;
    private static DefaultTableModel mod_table;
    private static Cliente client_selected;
    private static Date date;
    public JFrameTarea() {
        String titles[] = { "ID", "NOMBRE","CANTIDAD","PRECIO","SUBTOTAL"};
        initComponents();
        tbl_articles.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setPreferredSize(new Dimension(870, tbl_articles.getPreferredSize().height));
        mod_table = new DefaultTableModel(null, titles);
        tbl_articles.setModel(mod_table);
        tbl_articles.getColumnModel().getColumn(0).setPreferredWidth(150);
        tbl_articles.getColumnModel().getColumn(1).setPreferredWidth(427);
        tbl_articles.getColumnModel().getColumn(2).setPreferredWidth(150);
        tbl_articles.getColumnModel().getColumn(3).setPreferredWidth(150);
        tbl_articles.getColumnModel().getColumn(4).setPreferredWidth(150);
        
        setLocationRelativeTo(null);
        centerPanel.setOpaque(true);
        centerPanel.setBorder(
            BorderFactory.createTitledBorder("  "));
        container_2.setOpaque(true);
        container_2.setBorder(
            BorderFactory.createTitledBorder("Información del articulo"));
        container_3.setOpaque(true);
        container_3.setBorder(
            BorderFactory.createTitledBorder("Datos del cliente"));
        container_4.setOpaque(true);
        container_4.setBorder(
            BorderFactory.createTitledBorder("Empleado"));
        txt_date.setEnabled(false);
        date = Date.valueOf(LocalDate.now());
        txt_date.setText(date.toString());
        //_------------------------
        
        DefaultComboBoxModel box_model = new DefaultComboBoxModel();
        ArrayList<Empleado> workers_list = new ArrayList<Empleado>();
        workers_list = EmpleadoDAO.listar();
        for (Empleado empleado : workers_list) {
            box_model.addElement(empleado.getNombre());
            idlist_workers.add(empleado.getIdemp());
        }
        cbo_workers.setModel(box_model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        centerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_article = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_article = new javax.swing.JList<>();
        container_2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_headOrder = new javax.swing.JTextField();
        txt_articleCode = new javax.swing.JTextField();
        txt_articleName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_date = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_articleDescription = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        txt_articlePrice = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_articles = new javax.swing.JTable();
        container_3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txt_clientID = new javax.swing.JTextField();
        txt_clientName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_allName = new javax.swing.JTextField();
        container_4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        cbo_workers = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txt_quant = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_totalPrice = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 153));

        jLabel1.setText("Iniciales");

        txt_article.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_articleKeyReleased(evt);
            }
        });

        list_article.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list_articleMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(list_article);

        javax.swing.GroupLayout centerPanelLayout = new javax.swing.GroupLayout(centerPanel);
        centerPanel.setLayout(centerPanelLayout);
        centerPanelLayout.setHorizontalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(centerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txt_article, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        centerPanelLayout.setVerticalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_article, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel2.setText("Código");

        jLabel3.setText("N° Pedido");

        jLabel4.setText("Fecha");

        jLabel5.setText("Nombre");

        jLabel6.setText("Descripción");

        txt_articleDescription.setColumns(20);
        txt_articleDescription.setRows(5);
        jScrollPane3.setViewportView(txt_articleDescription);

        jLabel7.setText("Precio");

        jButton1.setText("Quitar Item");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Agregar Item");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout container_2Layout = new javax.swing.GroupLayout(container_2);
        container_2.setLayout(container_2Layout);
        container_2Layout.setHorizontalGroup(
            container_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, container_2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(container_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, container_2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, container_2Layout.createSequentialGroup()
                        .addGroup(container_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(container_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(container_2Layout.createSequentialGroup()
                                .addComponent(txt_articleCode, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(container_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(51, 51, 51)
                                .addGroup(container_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_headOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txt_articleName))))
                .addGap(35, 35, 35))
            .addGroup(container_2Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(txt_articlePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        container_2Layout.setVerticalGroup(
            container_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(container_2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(container_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_articleCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txt_headOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(container_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(container_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_articleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(container_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_articlePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(47, 47, 47))
        );

        tbl_articles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_articles);

        jLabel9.setText("Cliente");

        txt_clientName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_clientNameKeyReleased(evt);
            }
        });

        jLabel10.setText("Nombres");

        javax.swing.GroupLayout container_3Layout = new javax.swing.GroupLayout(container_3);
        container_3.setLayout(container_3Layout);
        container_3Layout.setHorizontalGroup(
            container_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(container_3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(container_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(container_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(container_3Layout.createSequentialGroup()
                        .addComponent(txt_clientID, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(txt_clientName, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txt_allName))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        container_3Layout.setVerticalGroup(
            container_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(container_3Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(container_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_clientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_clientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(container_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_allName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(38, 38, 38))
        );

        jLabel11.setText("Nombre");

        cbo_workers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbo_workers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbo_workersMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout container_4Layout = new javax.swing.GroupLayout(container_4);
        container_4.setLayout(container_4Layout);
        container_4Layout.setHorizontalGroup(
            container_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(container_4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(container_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(cbo_workers, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        container_4Layout.setVerticalGroup(
            container_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(container_4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbo_workers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setText("Cantidad");

        jLabel12.setText("Total  S/.");

        jButton3.setText("Registrar Pedido");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(container_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(container_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_totalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jButton3)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(centerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabel8)
                                        .addGap(30, 30, 30)
                                        .addComponent(txt_quant, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(container_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(container_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(centerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_quant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(container_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(container_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txt_totalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_articleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_articleKeyReleased
        String content = txt_article.getText().toLowerCase();
        DefaultListModel list_model;
        if(!content.isEmpty()){
            list_articles = ArticuloDAO.buscarPorNombre(content);
             list_model = new DefaultListModel();
            for (Articulo article : list_articles) {
                list_model.addElement(article.getNombre());
            }
            
        } else {
             list_model = new DefaultListModel();
             this.cleanInputs();
        }
        list_article.setModel(list_model);
    }//GEN-LAST:event_txt_articleKeyReleased
    public void cleanInputs(){
        txt_articleCode.setText(null);
        txt_articleName.setText(null);
        txt_articleDescription.setText(null);
        txt_articlePrice.setText(null);
    }
    private void list_articleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_articleMouseClicked
        String list_selected = list_article.getSelectedValue();
        if(list_selected != null){
            for (Articulo article : list_articles) {
                if(article.getNombre().equals(list_selected)){
                    article_selected = new Articulo();
                    article_selected.setIdart(article.getIdart());
                    article_selected.setNombre(article.getNombre());
                    article_selected.setDescripcion(article.getDescripcion());
                    article_selected.setFoto(article.getFoto());
                    article_selected.setPrecio(article.getPrecio());
                }
            }
            txt_articleCode.setText(String.valueOf(article_selected.getIdart()));
            txt_articleName.setText(article_selected.getNombre());
            txt_articleDescription.setText(article_selected.getDescripcion());
            txt_articlePrice.setText(String.valueOf(article_selected.getPrecio()));
            
        }
    }//GEN-LAST:event_list_articleMouseClicked
    public void totalPrice(){
       double a = 0;
       for (int i = 0; i < tbl_articles.getRowCount(); i++) {
           a += Double.parseDouble(tbl_articles.getValueAt(i , 4).toString());
       } 
       txt_totalPrice.setText(String.valueOf(a));
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            boolean flag = false;
            int aux = 0;
            if(tbl_articles.getRowCount() > 0){
                for (int i = 0; i < tbl_articles.getRowCount(); i++) {
                    System.out.println(tbl_articles.getValueAt(i , 0));
                    if(article_selected.getIdart() == Integer.parseInt(tbl_articles.getValueAt(i , 0).toString())){
                      flag = true;
                      aux = i;
                    } 
                }
                if(flag){
                    tbl_articles.setValueAt(Integer.parseInt(tbl_articles.getValueAt(aux , 2).toString()) + Integer.parseInt(txt_quant.getText()), aux , 2);
                    tbl_articles.setValueAt(Double.parseDouble(tbl_articles.getValueAt(aux, 2).toString()) * Double.parseDouble(tbl_articles.getValueAt(aux, 3).toString()), aux, 4);
                } else {
                    String quant = txt_quant.getText();
                    mod_table.addRow(new Object[] {  
                        article_selected.getIdart(),
                        article_selected.getNombre(),
                        quant,
                        article_selected.getPrecio(),
                        Integer.parseInt(quant)*article_selected.getPrecio()
                    });
                }

            } else {
                String quant = txt_quant.getText();
                mod_table.addRow(new Object[] {  
                    article_selected.getIdart(),
                    article_selected.getNombre(),
                    quant,
                    article_selected.getPrecio(),
                    Integer.parseInt(quant)*article_selected.getPrecio()
                });
            }

            totalPrice();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error con los datos");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       ((DefaultTableModel)tbl_articles.getModel()).removeRow(tbl_articles.getSelectedRow());
       totalPrice();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_clientNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_clientNameKeyReleased
        int key = evt.getKeyCode();
        if(key == KeyEvent.VK_ENTER){
            String name = txt_clientName.getText().toLowerCase();
            int id = Integer.parseInt(txt_clientID.getText());
            client_selected = new Cliente();
            client_selected = ClienteDAO.getClientByNameAndId(name, id);
            if(client_selected != null){
                txt_allName.setText(client_selected.getNombres());
            } else {
                txt_allName.setText("");
            }
            
        }
    }//GEN-LAST:event_txt_clientNameKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            PedidoDAO.insertOrder(Integer.parseInt(txt_headOrder.getText()), date , Double.parseDouble(txt_totalPrice.getText()),
               idlist_workers.get(index) , Integer.parseInt(txt_clientID.getText()));
            for (int i = 0; i < tbl_articles.getRowCount(); i++) {
                PedidoDAO.insertDetailOrder(Integer.parseInt(tbl_articles.getValueAt(i, 0).toString()), Integer.parseInt(txt_headOrder.getText()),
                        Double.parseDouble(tbl_articles.getValueAt(i, 3).toString()),
                        Integer.parseInt(tbl_articles.getValueAt(i, 2).toString()), 
                        Double.parseDouble(tbl_articles.getValueAt(i, 4).toString()));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error con los datos");
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cbo_workersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbo_workersMouseClicked
        index = cbo_workers.getSelectedIndex();
    }//GEN-LAST:event_cbo_workersMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameTarea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbo_workers;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JPanel container_2;
    private javax.swing.JPanel container_3;
    private javax.swing.JPanel container_4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> list_article;
    private javax.swing.JTable tbl_articles;
    private javax.swing.JTextField txt_allName;
    private javax.swing.JTextField txt_article;
    private javax.swing.JTextField txt_articleCode;
    private javax.swing.JTextArea txt_articleDescription;
    private javax.swing.JTextField txt_articleName;
    private javax.swing.JTextField txt_articlePrice;
    private javax.swing.JTextField txt_clientID;
    private javax.swing.JTextField txt_clientName;
    private javax.swing.JTextField txt_date;
    private javax.swing.JTextField txt_headOrder;
    private javax.swing.JTextField txt_quant;
    private javax.swing.JTextField txt_totalPrice;
    // End of variables declaration//GEN-END:variables
}
